name: connectivity-graph

channels:
  - conda-forge
 
dependencies:
  - Python>=3.10,<4.0
  - mamba
  - ipycytoscape
  - networkx
  - igraph
  - pip
  - pip:
    - https://github.com/AnatomicMaps/map-knowledge/releases/download/v0.13.2/mapknowledge-0.13.2-py3-none-any.whl