name: connectivity-graph_environment

channels:
  - defaults
  - conda-forge
 
dependencies:
  - python=3.8
  - mamba
  - ipycytoscape
  - networkx
  - mapknowledge
  - pip
  - pip:
    - poetry==1.2.2