name: connectivity-graph_environment

channels:
  - defaults
  - conda-forge
 
dependencies:
  - python>=3.8,<4.0
  - mamba
  - ipycytoscape
  - networkx
  - pip
  - pip:
    - https://github.com/AnatomicMaps/map-knowledge/releases/download/v0.13.2/mapknowledge-0.13.2-py3-none-any.whl